function qos = sDefaultQosBestEffort(~)
% sDefaultQosBestEffort Return QoS settings for non-critical ROS2 streams.

    qos = struct( ...
        "Reliability", "besteffort", ...
        "Durability", "volatile" ...
    );
end