function pc = sEmptyPointCloud(~)
%sEmptyPointCloud Persistent empty PointCloud struct template.

    persistent EMPTY_PC
    if isempty(EMPTY_PC)
        EMPTY_PC = struct( ...
            "TimestampSec", 0.0, ...
            "FrameId", "", ...
            "XYZ", zeros(0, 3, "single"), ...
            "HasColor", false, ...
            "Color", zeros(0, 3, "uint8") ...
        );
    end
    pc = EMPTY_PC;
end
