function pose = sEmptyPose(~)
%sEmptyPose Persistent empty Pose struct template.

    persistent EMPTY_POSE
    if isempty(EMPTY_POSE)
        EMPTY_POSE = struct( ...
            "TimestampSec", 0.0, ...
            "FrameId", "", ...
            "ChildFrameId", "", ...
            "Position", [NaN NaN NaN], ...
            "OrientationEuler", [NaN NaN NaN], ...
            "PoseCovariance", NaN(6, 6), ...
            "TwistCovariance", NaN(6, 6) ...
        );
    end
    pose = EMPTY_POSE;
end
