function imu = sEmptyImu(~)
%sEmptyImu Persistent empty IMU struct template.

    persistent EMPTY_IMU
    if isempty(EMPTY_IMU)
        EMPTY_IMU = struct( ...
            "TimestampSec", 0.0, ...
            "OrientationQuat", [NaN NaN NaN NaN], ... % [w x y z]
            "AngularVelocity", [NaN NaN NaN], ...
            "LinearAcceleration", [NaN NaN NaN], ...
            "OrientationCovariance", NaN(3, 3), ...
            "AngularVelocityCovariance", NaN(3, 3), ...
            "LinearAccelerationCovariance", NaN(3, 3) ...
        );
    end
    imu = EMPTY_IMU;
end
